### ISSUE TITLE
Prototyping-2

### ISSUE THREAD

**Issue by syedshahzebhasnain** [InteractiveAquariumOTN/InteractiveAquarium#14]

**Comment by syedshahzebhasnain** [comment]
Working on ways to make bubbles in the fish tank

**Comment by Abhikalra** [comment]
Exploring ways to add animation and transitions.Images of the types of fish are prepared. Need to add them as separate classes and animate the divisions in CSS.
Exploring opening of table on click event of fish image

**Comment by Abhikalra** [comment]
animation using CSS
-webkit used: works in chrome and not moz
-table structure with adjusted z-index added for reference
-images in individual divs
