### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by syedshahzebhasnain** [InteractiveAquariumOTN/InteractiveAquarium#15]

**Comment by jocelynmarielee** [comment]
options for names:
Tap n' Track Aquarium
Tap n' Track Tank
Fish Finder
Fish Follower
Sea Searcher

**Comment by jocelynmarielee** [comment]
[logo.pdf](https://github.com/InteractiveAquariumOTN/InteractiveAquarium/files/170506/logo.pdf)

**Comment by jocelynmarielee** [comment]
![tapntracklogo](https://cloud.githubusercontent.com/assets/17100115/13724162/72f6b3ca-e852-11e5-8ef9-051f43aa3d78.png)
