### ISSUE TITLE
design pop-up tabs

### ISSUE THREAD

**Issue by jocelynmarielee** [InteractiveAquariumOTN/InteractiveAquarium#23]

**Comment by jocelynmarielee** [comment]
pop up tab/bubble for each sea creature

**Comment by sidhudeepinder** [comment]
@jocelynmarielee  I've designed a general pop-up using CSS, let me know if you are still going to design the pop-up.

**Comment by jocelynmarielee** [comment]
@sidhudeepinder @brittthalll is assigned to this
