### ISSUE TITLE
Background and layering

### ISSUE THREAD

**Issue by syedshahzebhasnain** [InteractiveAquariumOTN/InteractiveAquarium#30]

**Comment by sidhudeepinder** [comment]
@jocelynmarielee  can you provide me the different back ground images? I need those to implement the layering of images in the background. 
Thanks.

**Comment by jocelynmarielee** [comment]
@sidhudeepinder that was @brittthalll that did the background images layers I don't have them

**Comment by sidhudeepinder** [comment]
@brittthalll thanks for the plants, can you also let me know where to place them?
can you mark it on the background image?
